Dual-Finance/risk-manager

src/config.ts
src/scalper.ts

@brittcyr Ready for risk manager DIP feed/input
Other remaining Todo's are mostly systems level:
TODO setup process to restart at 12:01 UTC each day
TODO Reconnect logic
TODO run on Serum using RLP collateral

Multiple Product Support

---

src/common.ts
src/config.ts
src/main.ts
src/poller.ts
src/router.ts
src/scalper.ts
src/utils.ts

Automatically poll for multiple assets

---

.gitignore
package.json
src/common.ts
src/config.ts
src/main.ts
src/router.ts
src/utils.ts

TODO in a follow up
Compare the prices of API vs fallback
Status reporting to a health monitoring service
Handle token program failure or API failure
Automated testing

Route API orders

---

src/config.ts
src/main.ts
src/scalper.ts
src/utils.ts

https://github.com/Dual-Finance/risk-manager/issues/25

randomness introduced into rerun & twap timers

---

src/poller.ts

https://github.com/Dual-Finance/risk-manager/issues/40

catch poller errors

---

src/scalper.ts

Updated RPC, Event listeners & error handling

Performance

---

src/config.ts
src/scalper.ts

Plan to loan RM ~100 SOL to avoid any risk of liquidation for now. This can also serve as the start for integration into Serum when we get there. Hedging with spot rather than perps

Allow delta offsets for loans

---

src/config.ts
src/scalper.ts

Fixes https://github.com/Dual-Finance/risk-manager/issues/59
Better implementation would be to check if mango is up, not a manual switch

mango downtime

---

package.json
src/config.ts
src/main.ts
src/markets.json
src/router.ts
src/scalper.ts
src/scalper_utils.ts
src/serumVial.ts
yarn.lock

Not yet ready, but a preview of what I did for a major refactor along with the skeleton of supporting serum
There are some TODO that I have put in there which should be resolved before submitting

Serum Integration

---

src/scalper.ts

Set successive fair values for scalps equal to the prior scalp price

prior fill fair value

---

src/config.ts
src/scalper.ts
src/scalper_utils.ts

fixes a bug where all the oracles failed and there is a very wide market on openbook so our gamma prices are around a bad theo value

handle wide markets

---

src/scalper.ts

fixes https://github.com/Dual-Finance/risk-manager/issues/72

widen successive gamma scalps

---

README.md
src/config.ts
src/scalper.ts

use cli env vars for sensitive constants

environment vars

---

package-lock.json
package.json
src/common.ts
src/config.ts
src/scalper.ts
src/scalper_utils.ts
src/utils.ts
yarn.lock

Use jupiter to avoid getting picked off on illiquid tokens

Jupiter Integration

---

package-lock.json
src/config.ts
src/router.ts
yarn.lock

fixes https://github.com/Dual-Finance/risk-manager/issues/94

min execution premium for MM

---

src/scalper.ts

try catch around loading markets

---

src/config.ts
src/scalper.ts

remove USD const, use a fct of the gamma

dimQty as a fct of maxBackGammaMultiple

---

src/config.ts
src/ids.json
src/poller.ts
src/router.ts
src/scalper.ts

Use processed as commitment to reduce lag in MM fills and sync to use ENV rpc

rpc clean up

---

src/config.ts
src/ids.json
src/main.ts
src/poller.ts
src/router.ts
src/scalper.ts

Check MM quotes vs positions on each re-run.
WIP because haven't been able to test live against MM quotes until they're back on. 
Maybe there's a more efficient way than effectively duplicating the route fct, but without run_risk_manager()?

Check quotes on rerun

---

src/config.ts
src/ids.json
src/main.ts
src/poller.ts
src/router.ts
src/scalper.ts

Allow zscore default of 80% CI to be overridden to widen spreads for illiquid tokens

Zscore env

---

README.md
src/config.ts
src/main.ts
src/poller.ts
src/scalper.ts
src/scalper_utils.ts
src/serumVial.ts
src/utils.ts

No urgent changes. Running locally

BONK support & MODE env

---

src/config.ts
src/router.ts
src/scalper.ts

Fixes https://github.com/Dual-Finance/risk-manager/issues/109

routing pricing fix

---

src/main.ts
src/poller.ts
src/router.ts

The quantity is the important one, was dividing by too big of a number

Poller fix

---

src/config.ts
src/constants.ts
src/scalper.ts
src/scalper_utils.ts
src/utils.ts

And some small other no-op changes

Use a symbol type so it is clearer what changes when adding new tokens

---

src/config.ts
src/constants.ts
src/main.ts
src/router.ts
src/scalper.ts
src/scalper_utils.ts
src/utils.ts

Mostly just cleanups and adjusting wait times when we are not doing randomness for the rerun.

Various fixes and code cleanups

---

src/scalper.ts

Fixes issue currently where price is < high strike but we were still adjusting the gamma bid not gamma offer

use min & max strikes for isOTM

---

src/constants.ts
src/scalper.ts
src/scalper_utils.ts

Mostly no-op cleanups but also a few minor bug fixes, like openbook settlement

Cleanup in scalper

---

src/scalper.ts
src/scalper_utils.ts

Consolidating repeated logic
Changing behavior for if cancels fail, do not place new bids
Small changes in rounding/floor on pricing
Otherwise intended no-op changes

More cleanup

---

src/config.ts
src/scalper.ts

Fixes https://github.com/Dual-Finance/risk-manager/issues/139
Also corrects incorrect min whale ask

Reduce order size based on inventory

---

src/scalper.ts

Intended to be no-op changes and removing redundant checks except
remove try catch around delta hedge, if that fails, we dont want to continue
change the waitForFill, will clean that up in more places and fix this one in a follow up

First pass at cleaning up delta hedging on openbook logic

---

src/scalper.ts

This is intended to be comment and logging changes and no-op changes only.

Some cleanup in gamma scalp open book

---

src/config.ts

Preemptively updating position for MNGO Buyback 5. Will sit on this until confirmed

Updating mngo position

---

src/poller.ts
src/router.ts

Use optional deposit in CheckMM so that poller still routes new deposits

Use poller deposit callback

---

src/config.ts
src/scalper_utils.ts

Seperating out each feature. Expect a few bite sized PRs

Price Override

---

src/router.ts
src/router_utils.ts

This allows removing a ts-ignore

Give a type to getPriceResponse

---

src/config.ts

Testing for Mango BTC perps to run on aws

btc position update

---

src/mango.ts
src/mango_utils.ts
src/scalper.ts
src/scalper_utils.ts

Helper function for fills feeds
Adds priority fees

Mango utils & todos

---

src/config.ts
src/router.ts

@brittcyr given the potential issues testing this looking for feedback up to this point. Main ToDo is on the poller side either moving to a timed check or a delay after AccountChangeCallback

Handle Routing Partial Fills

---

src/config.ts
src/scalper.ts
src/scalper_utils.ts

Allows for more than just BONK SO to be liquidated

Support multiple liquidation symbols

---

src/config.ts
src/scalper_utils.ts
src/utils.ts

The oracle change supports DUAL switchboard price which max period is 300 sec

Filter expired positions & less frequent oracle

---

src/mango.ts

Fetch a one hour funding rate instead of just using instantaneous

---

src/mango.ts
src/scalper.ts

remove is_dev hacks for forcing volume

---

src/config.ts

Remove expired treasury positions

---

src/config.ts
src/mango.ts
src/oracle.ts
src/scalper.ts
src/scalper_utils.ts
src/utils.ts

Remove unused import
Cleanup config names
Refactor ELIGIBLE_SO_STATES
Cleanup scoping in oracle
Reduce excessive CU request

Various small cleanups
